<a href="https://colab.research.google.com/github/sumitprojects/python-projects/blob/master/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

<img src='https://numpy.org/_static/numpy_logo.png'>

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

https://numpy.org/


### Installation

pip install numpy

In [0]:
!pip install numpy

#### Using numpy

In [0]:
import numpy as np # np is just an alias

#### Numpy Arrays

Two forms of numpy arrays:

* Vectors - 1-Dimensional
* Matrices - 2-Dimensional

### Creating numpy arrays

* From Python List

In [0]:
lst = [1,2,3,4,5]

lst

[1, 2, 3, 4, 5]

In [0]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [0]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in methods for numpy array

#### arange : Returns evenly spaced values within a given interval

In [0]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,31,30)

array([ 0, 30])

#### zeros and ones
Generate arrays of zeros and ones

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones(4)

array([1., 1., 1., 1.])

In [0]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### linspace
Returns evenly spaced numbers over a specified interval

In [0]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [0]:
np.linspace(0,31,30)

array([ 0.        ,  1.06896552,  2.13793103,  3.20689655,  4.27586207,
        5.34482759,  6.4137931 ,  7.48275862,  8.55172414,  9.62068966,
       10.68965517, 11.75862069, 12.82758621, 13.89655172, 14.96551724,
       16.03448276, 17.10344828, 18.17241379, 19.24137931, 20.31034483,
       21.37931034, 22.44827586, 23.51724138, 24.5862069 , 25.65517241,
       26.72413793, 27.79310345, 28.86206897, 29.93103448, 31.        ])

#### eye
Creates an identity matrix

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random

Numpy has lots of ways to create random number arrays

* rand
* randn
* randint

#### rand
Create and array of the given shape and populate it with the random samples from a uniform distribution over [0,1]

In [0]:
np.random.rand(10)

array([0.14034719, 0.30364055, 0.75529382, 0.41515395, 0.4046623 ,
       0.4331461 , 0.97161157, 0.0489634 , 0.52316006, 0.11840016])

In [0]:
np.random.rand(5,5)

array([[0.6893528 , 0.03760129, 0.54858458, 0.81170793, 0.25080827],
       [0.15680576, 0.11543732, 0.2890165 , 0.80941325, 0.80684248],
       [0.71198892, 0.20435325, 0.62466737, 0.00113458, 0.79672636],
       [0.58602474, 0.23920803, 0.92323726, 0.33614319, 0.72494641],
       [0.13225834, 0.19519803, 0.41680453, 0.61985495, 0.09988669]])

#### randn
Creates a sample/samples from the standard normal distribution unlike rand which is uniform distribution

In [0]:
np.random.randn(2)

array([0.61694307, 1.00608518])

In [0]:
np.random.randn(4,4)

array([[ 1.49438127e+00,  8.80962972e-01, -8.56305550e-01,
        -4.14847269e-01],
       [ 3.84787545e-01,  1.89233459e+00, -9.04755694e-01,
        -5.15437670e-01],
       [ 3.79913938e-01, -6.26243274e-01,  1.31685942e+00,
        -5.31236016e-01],
       [-1.35986911e+00,  1.49506468e-01, -6.33982560e-01,
         1.84556045e-03]])

#### randint
Returns random integers from low (included) to high (excluded)

In [0]:
np.random.randint(0,100)

97

In [0]:
np.random.randint(1,100,10)

array([80, 14, 89, 21, 43, 50, 44, 64, 31, 23])

### Array attributes and methods

In [0]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr

array([ 0,  1,  5, 46, 45, 11,  3, 14, 21, 29])

### Reshape

Returns an array containing same data but different shape

In [0]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max, min,argmax,argmin

Useful methods to find minimum and maximum values or index locations.

In [0]:
ranarr

array([ 0,  1,  5, 46, 45, 11,  3, 14, 21, 29])

In [0]:
ranarr.max()

46

In [0]:
ranarr.argmax()

3

In [0]:
ranarr.min()

0

In [0]:
ranarr.argmin()

0

### Shape
Shape is an attribute that arrays have

In [0]:
arr.shape

(25,)

In [0]:
arr.reshape(1,25).shape

(1, 25)

In [0]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Data type of object in array

In [0]:
arr.dtype

dtype('int64')

# Great Job !!