<a href="https://colab.research.google.com/github/sumitprojects/python-projects/blob/master/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

<img src='https://numpy.org/_static/numpy_logo.png'>

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

https://numpy.org/


### Installation

pip install numpy

In [1]:
!pip install numpy

#### Using numpy

In [0]:
import numpy as np # np is just an alias

#### Numpy Arrays

Two forms of numpy arrays:

* Vectors - 1-Dimensional
* Matrices - 2-Dimensional

### Creating numpy arrays

* From Python List

In [3]:
lst = [1,2,3,4,5]

lst

[1, 2, 3, 4, 5]

In [4]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [5]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in methods for numpy array

#### arange : Returns evenly spaced values within a given interval

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,31,30)

array([ 0, 30])

#### zeros and ones
Generate arrays of zeros and ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### linspace
Returns evenly spaced numbers over a specified interval

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,31,30)

array([ 0.        ,  1.06896552,  2.13793103,  3.20689655,  4.27586207,
        5.34482759,  6.4137931 ,  7.48275862,  8.55172414,  9.62068966,
       10.68965517, 11.75862069, 12.82758621, 13.89655172, 14.96551724,
       16.03448276, 17.10344828, 18.17241379, 19.24137931, 20.31034483,
       21.37931034, 22.44827586, 23.51724138, 24.5862069 , 25.65517241,
       26.72413793, 27.79310345, 28.86206897, 29.93103448, 31.        ])

#### eye
Creates an identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random

Numpy has lots of ways to create random number arrays

* rand
* randn
* randint

#### rand
Create and array of the given shape and populate it with the random samples from a uniform distribution over [0,1]

In [16]:
np.random.rand(10)

array([0.7876301 , 0.3834022 , 0.67757795, 0.5322528 , 0.13675718,
       0.15765824, 0.47399646, 0.94958151, 0.05947566, 0.0904748 ])

In [17]:
np.random.rand(5,5)

array([[0.16347089, 0.10663875, 0.27196645, 0.36300345, 0.52810264],
       [0.28114162, 0.41401443, 0.15385206, 0.36347897, 0.97875438],
       [0.19300253, 0.78466081, 0.52335821, 0.71170108, 0.11160373],
       [0.57149061, 0.69188678, 0.64696674, 0.57258861, 0.89416493],
       [0.57397108, 0.15507084, 0.50075691, 0.76752013, 0.62074379]])

#### randn
Creates a sample/samples from the standard normal distribution unlike rand which is uniform distribution

In [18]:
np.random.randn(2)

array([0.80619359, 0.5233807 ])

In [19]:
np.random.randn(4,4)

array([[-1.24608359,  1.06017413, -0.55649202,  0.85525937],
       [-0.28757841,  0.76354165,  0.39220929, -0.68843735],
       [-0.58855344,  0.19332342, -0.05121918,  0.10866021],
       [-0.98193474, -0.86288538,  0.86468409, -1.88508482]])

#### randint
Returns random integers from low (included) to high (excluded)

In [20]:
np.random.randint(0,100)

37

In [21]:
np.random.randint(1,100,10)

array([66,  7, 96, 21, 44, 44,  3, 71, 68,  6])

### Array attributes and methods

In [0]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([48, 17, 30, 10, 38,  7, 30, 43, 41, 13])

### Reshape

Returns an array containing same data but different shape

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max, min,argmax,argmin

Useful methods to find minimum and maximum values or index locations.

In [26]:
ranarr

array([48, 17, 30, 10, 38,  7, 30, 43, 41, 13])

In [27]:
ranarr.max()

48

In [28]:
ranarr.argmax()

0

In [29]:
ranarr.min()

7

In [30]:
ranarr.argmin()

5

### Shape
Shape is an attribute that arrays have

In [31]:
arr.shape

(25,)

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Data type of object in array

In [34]:
arr.dtype

dtype('int64')

# Great Job !!