<a href="https://colab.research.google.com/github/sumitprojects/python-projects/blob/master/Numpy_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arr = np.arange(0,11)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

In [0]:
arr[9]

9

In [0]:
arr[:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[1:5]

array([1, 2, 3, 4])

### Broadcasting

Numpy arrays will differ from normal python list because of their ability to broadcast

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[0:5] = 99

In [0]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [0]:
slicearr = arr[0:6]
slicearr

array([99, 99, 99, 99, 99,  5])

In [0]:
slicearr[:] = 100
slicearr

array([100, 100, 100, 100, 100, 100])

In [0]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [0]:
arr_copy = arr.copy()

arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

### Selection

In [0]:
arr = np.arange(1,11)

In [0]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
barr = arr > 4

In [0]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
arr[barr]

array([ 5,  6,  7,  8,  9, 10])

## shallow and deep copy

In [0]:
xx = [[1,2,3],[4,5,6],[7,8,9]]
yy = list(xx) # Making a shallow copy

The above operation is shallow copy

yy will be a new and independent object with same content as xx.

In [0]:
xx

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
yy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
xx.append(['new list nested'])

In [0]:
xx

[[1, 2, 3], [4, 5, 6], [7, 8, 9], ['new list nested']]

In [0]:
yy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
xx[1][0] = 99999

In [0]:
xx

[[1, 2, 3], [99999, 5, 6], [7, 8, 9], ['new list nested']]

In [0]:
yy

[[1, 2, 3], [99999, 5, 6], [7, 8, 9]]

### Deep Copy

In [0]:
import copy

In [0]:
xxd =[[1,2,3],[4,5,6],[7,8,9]]
zz = copy.deepcopy(xxd)


In [0]:
xxd

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
zz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
xxd[1][0] ='XXXXX'

In [0]:
xxd

[[1, 2, 3], ['XXXXX', 5, 6], [7, 8, 9]]

In [0]:
zz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]